server:
  port: 8081

dubbo:
  scan:
    base-packages: org.apache.dubbo.demo
  application:
    qos-enable: false
    logger: slf4j
    name: dubbo-demo-consumer
    owner: dev
  config-center:
    timeout: 10000
    address: etcd://127.0.0.1:2379
    group: test
  metadata-report:
    address: etcd://127.0.0.1:2379
  registry:
    timeout: 10000
    address: etcd3://127.0.0.1:2379
  consumer:
    group: test
    version: 1.0.0
    check: false